import type { Metadata } from "next";
import { Inter, Montserrat, Poppins, Playfair_Display } from "next/font/google";
import "./globals.css";
import NavbarDesktop from "@/components/NavbarDesktop";
import NavbarMobile from "@/components/NavbarMobile";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
``;
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <div className="h-fit relative">
          <NavbarMobile />
          <NavbarDesktop />
          <div className="max-w-[1920px] m-auto">{children}</div>
        </div>
      </body>
    </html>
  );
}
